use serde::{Deserialize, Serialize};
use std::fmt;
use uuid::Uuid;

/// Unique, unforgeable identifier for an agent process.
///
/// Generated by the kernel at spawn time. Cannot be constructed
/// from arbitrary values outside the kernel.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct AgentId(Uuid);

impl AgentId {
    /// Create a new random AgentId. Should only be called by the runtime.
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    /// Construct an AgentId from an explicit UUID. Only for privileged callers
    /// that need a stable identity across restarts (e.g., Bootstrap Agent
    /// persisted via `AAOS_BOOTSTRAP_ID`). Normal agents should use `new()`
    /// so IDs remain unforgeable.
    pub fn from_uuid(uuid: Uuid) -> Self {
        Self(uuid)
    }

    pub fn as_uuid(&self) -> &Uuid {
        &self.0
    }
}

impl Default for AgentId {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for AgentId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn agent_ids_are_unique() {
        let a = AgentId::new();
        let b = AgentId::new();
        assert_ne!(a, b);
    }

    #[test]
    fn agent_id_roundtrips_json() {
        let id = AgentId::new();
        let json = serde_json::to_string(&id).unwrap();
        let parsed: AgentId = serde_json::from_str(&json).unwrap();
        assert_eq!(id, parsed);
    }
}
